### ISSUE TITLE
CentOS/Redhat SSH jail needs to check /var/log/secure, not /var/log/auth.log

### ISSUE THREAD

**Issue by sigio** [resmo/ansible-role-fail2ban#5]
Fail2ban won't start on a fresh RHEL7 system, as there is no /var/log/auth.log.

My guess is the jail.local template needs to check for /var/log/secure on EL* systems, and /var/log/auth.log on debian/ubuntu systems

**Comment by marema31** [comment]
On Centos 7, removing the lines logpath= from the jail.local is sufficient 

All the paths are defined in /etc/fail2ban/paths-fedora.conf and /etc/fail2ban/paths-debian.conf.
And jail.conf contains a line "before= paths-fedora.conf". All theses files are provided by the EPEL package of fail2ban.

**Comment by sigio** [comment]
Yeah... I ran into some issues between centos/rhel 5, 6 and 7 ... but i've resolved those differently ;)

**Comment by sigio** [comment]
Yeah... I ran into some issues between centos/rhel 5, 6 and 7 ... but i've resolved those differently ;)

**Comment by silverfisk** [comment]
Getting the same problem when running it on Amazon Linux (which is pretty much EL6)
